id: IC449C728
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T14:05:30+00:00'
last_modified: '2022-06-07T09:08:42.043890+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22609
  title: དམ་ཆོས་དགོངས་པ་ཡང་ཟབ་ཀྱི་ཆོས་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6478':
      image_group_id: I1KG22617
      title: ''
      total_pages: 510
      order: 1
      base_file: 6478.txt
    '4753':
      image_group_id: I1KG22618
      title: ''
      total_pages: 880
      order: 2
      base_file: 4753.txt
    E21E:
      image_group_id: I1KG22619
      title: ''
      total_pages: 570
      order: 3
      base_file: E21E.txt
    66A7:
      image_group_id: I1KG22620
      title: ''
      total_pages: 594
      order: 4
      base_file: 66A7.txt
    '9192':
      image_group_id: I1KG22621
      title: ''
      total_pages: 586
      order: 5
      base_file: 9192.txt
    '9484':
      image_group_id: I1KG22622
      title: ''
      total_pages: 476
      order: 6
      base_file: 9484.txt
    88B7:
      image_group_id: I1KG22623
      title: ''
      total_pages: 336
      order: 7
      base_file: 88B7.txt
    B0C7:
      image_group_id: I1KG22624
      title: ''
      total_pages: 200
      order: 8
      base_file: B0C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
